layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  # sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  # limit: 9
  # exclude:
  #   forks: true
  #   projects:
    # - repo-name
  list:
    - klausmeyer/docker-registry-browser
    - klausmeyer/ansible-mailserver
    - klausmeyer/ansible-homelab
    - klausmeyer/dotfiles
    - klausmeyer/fritzbox-smarthome
    - klausmeyer/inwx-update

social_media:
  # behance: your_username
  # facebook: your_username
  # dribbble: your_username
  # linkedin: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Ruby
    web_url: https://github.com/topics/ruby
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/ruby/ruby.png

  - name: Rails
    web_url: https://github.com/topics/rails
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/rails/rails.png

  - name: Elixir
    web_url: https://github.com/topics/elixir
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/elixir/elixir.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/docker/docker.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/aws/aws.png

  - name: Ansible
    web_url: https://github.com/topics/ansible
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/ansible/ansible.png

profiles:
  - name: Twitter
    link: http://twitter.com/onkelhotte

  - name: Xing
    link: https://www.xing.com/profile/Klaus_Meyer321
