layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Ruby
    web_url: https://github.com/topics/ruby
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/ruby/ruby.png

  - name: Rails
    web_url: https://github.com/topics/rails
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/rails/rails.png

  - name: Elixir
    web_url: https://github.com/topics/elixir
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/elixir/elixir.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/go/go.png

  - name: Mysql
    web_url: https://github.com/topics/mysql
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/mysql/mysql.png

  - name: Postgresql
    web_url: https://github.com/topics/postgresql
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/postgresql/postgresql.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/kubernetes/kubernetes.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/aws/aws.png

  - name: Ansible
    web_url: https://github.com/topics/ansible
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/ansible/ansible.png

profiles:
  - name: Twitter
    link: http://twitter.com/onkelhotte

  - name: Xing
    link: https://www.xing.com/profile/Klaus_Meyer321
